### ISSUE TITLE
Invalid JSON response. Bahn API change?

### ISSUE THREAD

**Issue by thigg** [derhuerst/db-prices-cli#4]
```
/usr/bin/node /path/prices.js
✔ From where? › Hamburg-Altona – score: 14.324 relevance: 1.824 stationcode: 8002553
✔ To where? › Berlin Hauptbahnhof – score: 14.284 relevance: 1.730 stationcode: 8011160
FetchError: invalid json response body at https://reiseauskunft.bahn.de/bin/query.exe/dn?tbpMode=1&date=%2B1&getstop=1 reason: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at /path/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /path/prices.js:62:25
    at async Promise.all (index 1)
    at async /path/prices.js:61:23 {
  type: 'invalid-json'
}
```

Is it still recommended to use this tool? I use it to regularly fetch prices for connections.

Thanks for this tool. This already helped me to gather very nice data with fahrpreisplotter <3

**Comment by derhuerst** [comment]
It seems that this is because the underlying API has been shut off or modified. Please follow https://github.com/juliuste/db-prices/issues/33 for updates.

**Comment by thigg** [comment]
Just FYI: I rewrote my tool using a branch of hafas-client, based on the bestPrices api. https://github.com/thigg/fahrpreis-plotter
